/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtbase.ui.outline;

import org.eclipse.ocl.examples.xtext.essentialocl.ui.outline.EssentialOCLOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class QVTbaseOutlineTreeProvider extends EssentialOCLOutlineTreeProvider
{
//	protected void _createNode(IOutlineNode parentNode, PredicateCS csPredicate) {
//		createNode(parentNode, csPredicate.getExpr());
//	}
}
