/**
 *
 * $Id$
 */
package test.simplerdbms.validation;

import org.eclipse.emf.common.util.EList;

import test.simplerdbms.Column;
import test.simplerdbms.Key;
import test.simplerdbms.Table;

/**
 * A sample validator interface for {@link test.simplerdbms.ForeignKey}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ForeignKeyValidator {
	boolean validate();

	boolean validateRefersTo(Key value);
	boolean validateColumns(EList<Column> value);
	boolean validateOwner(Table value);
}
