/**
 *
 * $Id$
 */
package test.simplerdbms.validation;

import org.eclipse.emf.common.util.EList;

import test.simplerdbms.Column;
import test.simplerdbms.Table;

/**
 * A sample validator interface for {@link test.simplerdbms.Key}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KeyValidator {
	boolean validate();

	boolean validateOwner(Table value);
	boolean validateColumn(EList<Column> value);
}
