/**
 *
 * $Id$
 */
package test.simplerdbms.validation;

import org.eclipse.emf.common.util.EList;

import test.simplerdbms.Column;
import test.simplerdbms.ForeignKey;
import test.simplerdbms.Key;
import test.simplerdbms.Schema;

/**
 * A sample validator interface for {@link test.simplerdbms.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateColumns(EList<Column> value);
	boolean validateSchema(Schema value);
	boolean validateKeys(EList<Key> value);
	boolean validateForeignKeys(EList<ForeignKey> value);
}
