/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtimperative.ui.outline;

import org.eclipse.qvtd.xtext.qvtcorebase.ui.outline.QVTcoreBaseOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class QVTimperativeOutlineTreeProvider extends QVTcoreBaseOutlineTreeProvider {
	
}
