/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.qvtd.doc.ui;

import com.google.inject.Injector;
import org.eclipse.qvtd.doc.minioclcs.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MiniOCLCSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtextActivator.getInstance().getInjector(XtextActivator.ORG_ECLIPSE_QVTD_DOC_MINIOCLCS);
	}
	
}
