/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.qvtd.doc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.qvtd.doc.MiniOCLCSRuntimeModule;
import org.eclipse.qvtd.doc.MiniOCLCSStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MiniOCLCSIdeSetup extends MiniOCLCSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MiniOCLCSRuntimeModule(), new MiniOCLCSIdeModule()));
	}
	
}
