<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtschedule" nsURI="http://www.eclipse.org/qvt/2017/QVTschedule"
    nsPrefix="qvts">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDatum" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedBy" upperBound="-1"
        eType="#//MappingAction" eOpposite="#//MappingAction/productions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//MappingAction" derived="true" eOpposite="#//MappingAction/requisites"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#T-qvtbase-TypedModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicMappingRegion" eSuperTypes="#//MappingRegion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtcore/model/QVTcore.ecore#T-qvtcore-Mapping">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The property to navigate from source to target."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CastEdge" eSuperTypes="#//NavigableEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="completeClass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-CompleteClass"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyDatums" upperBound="-1"
        eType="#//PropertyDatum" containment="true" eOpposite="#//PropertyDatum/classDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClassDatums" upperBound="-1"
        eType="#//ClassDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComposedNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Nameable #//Symbolable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//ScheduledRegion" eOpposite="#//ScheduledRegion/connections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionEnd" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ConnectionEnd may be the Node/Edge at the end of a NodeConnection/EdgeConnection."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionRole" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ConnectionRole defines which of many possible roles a connection plays"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatumConnection" abstract="true" eSuperTypes="#//Connection #//GraphEdge #//GraphNode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A DatumConnection establishes that one or more source edges/nodes are available for use by one or more target edges/nodes.&#xD;&#xA;Derivations refine the availability to edges or nodes, pass by value, optional existence or mandatory existence."/>
    </eAnnotations>
    <eTypeParameters name="CE">
      <eBounds eClassifier="#//ConnectionEnd"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionRole" lowerBound="1"
        eType="#//ConnectionRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEnds" ordered="false"
        upperBound="-1">
      <eGenericType eTypeParameter="#//DatumConnection/CE"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element #//GraphEdge ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Nameable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An edge is directed and abstracts any Node interconnection within a Region."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeRole" lowerBound="1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region" eOpposite="#//Region/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incomingEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeConnection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An EdgeConnection supports an existence dependency between the region(s) that produce a navigation edge&#xD;&#xA;and the region(s) that consume it."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Property"/>
    <eGenericSuperTypes eClassifier="#//DatumConnection">
      <eTypeArguments eClassifier="#//NavigableEdge"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionEdge" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="IteratedEdge" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="IteratorNode" eSuperTypes="#//VariableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadingRegion" eSuperTypes="#//Region"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingAction" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtcore/model/QVTcore.ecore#T-qvtcore-Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productions" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/producedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisites" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/requiredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingRegion" abstract="true" eSuperTypes="#//Region"/>
  <eClassifiers xsi:type="ecore:EClass" name="MicroMappingRegion" eSuperTypes="#//MappingRegion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingRegion" lowerBound="1"
        eType="#//MappingRegion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namePrefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolNameSuffix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedMappingRegion" eSuperTypes="#//MappingRegion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolNameSuffix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigableEdge" abstract="true" eSuperTypes="#//Edge #//ConnectionEnd">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An edge is directed and abstracts any Node interconnection within a Region."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnection" eType="#//EdgeConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeEdge" eType="#//NavigableEdge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Non-null if this edge is part of a bidirectional pair."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" upperBound="-1"
        eType="#//EdgeConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Property">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The property to navigate from source to target."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if this edge is the auto-created second half of a bidirectional pair."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationEdge" eSuperTypes="#//NavigableEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partial" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if this edge is a partial many-to-one relationship."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element #//ConnectionEnd #//GraphNode ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Nameable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="AbstractNode provides the analysis and status of a node in the pattern match or construction of a Mapping&#xD;&#xA;or Composite Region."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDatum" lowerBound="1"
        eType="#//ClassDatum">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Non-null if this edge is part of a bidirectional pair."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnection" eType="#//NodeConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/targetNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeRole" lowerBound="1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" upperBound="-1"
        eType="#//NodeConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/sourceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region" eOpposite="#//Region/nodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeConnection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A NodeConnection supports a data connection from one or more source nodes to one or more target nodes.&#xD;&#xA;The data connection has a data type for the elemental value transfer through the connection.&#xD;&#xA;A passed connection may be realized by a simple transient point-to-point linkage or&#xD;&#xA;a full buffer that accumulates all possible values. A used connection is not actually realized; it just ensures that&#xD;&#xA;all source values exist before any target value consumes the value recomputed at the target."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDatum" lowerBound="1"
        eType="#//ClassDatum">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Non-null if this edge is part of a bidirectional pair."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//DatumConnection">
      <eTypeArguments eClassifier="#//Node"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationRegion" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyNodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headNodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultNode" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternTypedNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternVariableNode" eSuperTypes="#//VariableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PredicateEdge" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDatum" lowerBound="1"
        eType="#//ClassDatum" eOpposite="#//ClassDatum/propertyDatums"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//PropertyDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//PropertyDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecursionEdge" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="Region" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element #//GraphNode ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Nameable #//Symbolable #//ToDOTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokingRegion" eType="#//ScheduledRegion"
        eOpposite="#//ScheduledRegion/regions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Role defines which of many possible roles an edge plays"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" lowerBound="1" eType="#//Phase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::CONSTANT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loaded" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::LOADED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="(phase = qvtschedule::Phase::SPECULATION) or (phase = qvtschedule::Phase::REALIZED)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="old" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="(phase = qvtschedule::Phase::CONSTANT) or (phase = qvtschedule::Phase::LOADED) or (phase = qvtschedule::Phase::PREDICATED) or (phase = qvtschedule::Phase::SPECULATED)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::PREDICATED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realized" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::REALIZED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speculated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::SPECULATED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speculation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::SPECULATION"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleModel" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadingRegion" lowerBound="1"
        eType="#//LoadingRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduledRegion" eType="#//ScheduledRegion"
        containment="true" eOpposite="#//ScheduledRegion/scheduleModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduledRegion" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true" eOpposite="#//Connection/region"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true" eOpposite="#//Region/invokingRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduleModel" lowerBound="1"
        eType="#//ScheduleModel" eOpposite="#//ScheduleModel/scheduledRegion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbolable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableNode" abstract="true" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Phase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Phase identifies the different processing phases of a mapping. The phases are ordered by decreasing&#xA;certainty, allowing the earlier to be chosen by a merge.&#xA;&#xA;NEW = REALIZED || SPECULATION&#xA;OLD = CONSTANT || LOADED || PREDICATED || SPECULATED"/>
    </eAnnotations>
    <eLiterals name="CONSTANT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unequivocably known as compile time constant"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LOADED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Known once input models loaded"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REALIZED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Known once a mapping has realized its results"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PREDICATED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not known, awaiting matching"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SPECULATION">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Awaiting other mappings to speculate"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SPECULATED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Known other mappings are speculating"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OTHER">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not known, nothing to do with mapping execution"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainUsage" instanceClassName="org.eclipse.qvtd.pivot.qvtcore.analysis.DomainUsage"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GraphEdge" instanceClassName="org.eclipse.qvtd.pivot.qvtbase.graphs.GraphStringBuilder.GraphEdge"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GraphNode" instanceClassName="org.eclipse.qvtd.pivot.qvtbase.graphs.GraphStringBuilder.GraphNode"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToDOTable" instanceClassName="org.eclipse.qvtd.pivot.qvtbase.graphs.ToDOT.ToDOTable"
      abstract="true" interface="true"/>
</ecore:EPackage>
