<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtschedule" nsURI="http://www.eclipse.org/qvt/2017/QVTschedule"
    nsPrefix="qvts">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDatum" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedBy" upperBound="-1"
        eType="#//MappingAction" eOpposite="#//MappingAction/productions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//MappingAction" derived="true" eOpposite="#//MappingAction/requisites"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//TypedModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="completeClass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//CompleteClass"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyDatums" upperBound="-1"
        eType="#//PropertyDatum" containment="true" eOpposite="#//PropertyDatum/classDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//ClassDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeRole" eSuperTypes="#//Role">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="EdgeRole defines which of many possible roles an edge plays"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingAction" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtcore/model/QVTcore.ecore#//Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productions" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/producedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisites" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/requiredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeRole" eSuperTypes="#//Role">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="NodeRole defines which of many possible roles an node plays"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDatum" lowerBound="1"
        eType="#//ClassDatum" eOpposite="#//ClassDatum/propertyDatums"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//PropertyDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//PropertyDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Role defines which of many possible roles an edge plays"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" lowerBound="1" eType="#//Phase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::CONSTANT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loaded" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::LOADED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="(phase = qvtschedule::Phase::SPECULATION) or (phase = qvtschedule::Phase::REALIZED)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="old" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="(phase = qvtschedule::Phase::CONSTANT) or (phase = qvtschedule::Phase::LOADED) or (phase = qvtschedule::Phase::PREDICATED) or (phase = qvtschedule::Phase::SPECULATED)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::PREDICATED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realized" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::REALIZED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speculated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::SPECULATED"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speculation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="phase = qvtschedule::Phase::SPECULATION"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Phase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Phase identifies the different processing phases of a mapping. The phases are ordered by decreasing&#xA;certainty, allowing the earlier to be chosen by a merge.&#xA;&#xA;NEW = REALIZED || SPECULATION&#xA;OLD = CONSTANT || LOADED || PREDICATED || SPECULATED"/>
    </eAnnotations>
    <eLiterals name="CONSTANT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unequivocably known as compile time constant"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LOADED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Known once input models loaded"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REALIZED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Known once a mapping has realized its results"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PREDICATED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not known, awaiting matching"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SPECULATION">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Awaiting other mappings to speculate"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SPECULATED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Known other mappings are speculating"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OTHER">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not known, nothing to do with mapping execution"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
</ecore:EPackage>
