<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://www.eclipse.org/qvt/2015/Schedule" nsPrefix="qvts">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDatum" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedBy" upperBound="-1"
        eType="#//MappingAction" eOpposite="#//MappingAction/productions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//MappingAction" derived="true" eOpposite="#//MappingAction/requisites"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//TypedModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="completeClass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//CompleteClass"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyDatums" upperBound="-1"
        eType="#//PropertyDatum" containment="true" eOpposite="#//PropertyDatum/classDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" lowerBound="1"
        eType="#//Schedule" eOpposite="#//Schedule/datums"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//ClassDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtcore/model/QVTcore.ecore#//Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productions" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/producedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisites" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/requiredBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" lowerBound="1"
        eType="#//Schedule" eOpposite="#//Schedule/actions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDatum" lowerBound="1"
        eType="#//ClassDatum" eOpposite="#//ClassDatum/propertyDatums"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//PropertyDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//PropertyDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datums" upperBound="-1"
        eType="#//ClassDatum" containment="true" eOpposite="#//ClassDatum/schedule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//MappingAction" containment="true" eOpposite="#//MappingAction/schedule"/>
  </eClassifiers>
</ecore:EPackage>
