/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtrelation.ui.contentassist;

import org.eclipse.qvtd.xtext.qvtrelation.ui.contentassist.AbstractQVTrelationProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QVTrelationProposalProvider extends AbstractQVTrelationProposalProvider {

}
