<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    xmi:id="P.qvtrelation" name="qvtrelation" nsURI="http://www.eclipse.org/qvt/2015/QVTrelation" nsPrefix="qvtr">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.DomainPattern" name="DomainPattern" eSuperTypes="../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.DomainPattern.templateExpression" name="templateExpression"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvttemplate/model/QVTtemplate.ecore#//TemplateExp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.Key" name="Key" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Key.identifies" name="identifies" lowerBound="1" eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="key"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Key.oppositePart" name="oppositePart" ordered="false" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="oppKey"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Key.part" name="part" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="key"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Key.transformation" name="transformation" eType="#T.qvtrelation.RelationalTransformation"
        transient="true" eOpposite="#p.qvtrelation.RelationalTransformation.ownedKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.Relation" name="Relation" eSuperTypes="../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="p.qvtrelation.Relation.isTopLevel" name="isTopLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Relation.operationalImpl" name="operationalImpl" ordered="false"
        upperBound="-1" eType="#T.qvtrelation.RelationImplementation" containment="true" eOpposite="#p.qvtrelation.RelationImplementation.relation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Relation.variable" name="variable" ordered="false" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Relation.when" name="when" eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//Pattern"
        containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="whenOwner"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.Relation.where" name="where" eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//Pattern"
        containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="whereOwner"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.RelationCallExp" name="RelationCallExp" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//OCLExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationCallExp.argument" name="argument" lowerBound="2" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//OCLExpression" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="relationCallExp"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationCallExp.referredRelation" name="referredRelation" lowerBound="1"
        eType="#T.qvtrelation.Relation">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="relationCallExp"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.RelationDomain" name="RelationDomain" eSuperTypes="../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationDomain.defaultAssignment" name="defaultAssignment"
        ordered="false" upperBound="-1" eType="#T.qvtrelation.RelationDomainAssignment" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="owner"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationDomain.pattern" name="pattern" upperBound="-1" eType="#T.qvtrelation.DomainPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationDomain.rootVariable" name="rootVariable" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.RelationDomainAssignment" name="RelationDomainAssignment" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationDomainAssignment.valueExp" name="valueExp" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//OCLExpression" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="domainAssignment"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationDomainAssignment.variable" name="variable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Variable">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="domainAssignment"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.RelationImplementation" name="RelationImplementation" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationImplementation.impl" name="impl" lowerBound="1" eType="ecore:EClass ../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationImplementation.inDirectionOf" name="inDirectionOf"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//TypedModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationImplementation.relation" name="relation" eType="#T.qvtrelation.Relation"
        transient="true" eOpposite="#p.qvtrelation.Relation.operationalImpl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.RelationModel" name="RelationModel" eSuperTypes="../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//BaseModel"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.RelationalTransformation" name="RelationalTransformation" eSuperTypes="../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#//Transformation">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="p.qvtrelation.RelationalTransformation.ownedKey" name="ownedKey" ordered="false"
        upperBound="-1" eType="#T.qvtrelation.Key" containment="true" eOpposite="#p.qvtrelation.Key.transformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.SharedVariable" name="SharedVariable" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="T.qvtrelation.TemplateVariable" name="TemplateVariable" eSuperTypes="../../org.eclipse.ocl.pivot/model/Pivot.ecore#//Variable"/>
</ecore:EPackage>
