/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.eclipse.qvtd.doc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MiniOCLCSStandaloneSetup extends MiniOCLCSStandaloneSetupGenerated {

	def static void doSetup() {
		new MiniOCLCSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
