setpref complianceLevel=1.5

# We import a target definition which will be our API Base Line
importtargetdefinition "file://${checkout.location}/org.eclipse.qvtd.git/releng/org.eclipse.qvtd.releng.buckminster/APIBaseLine.target"
addbaseline -A "Eclipse QVTd API Base Line"

# We set the path of the new target platform
setpref targetPlatformPath="${checkout.location}/buildroot/target.platform"

import --properties "${checkout.location}/buildroot/build.properties" "org.eclipse.qvtd.git/releng/org.eclipse.qvtd.releng.buckminster/releng/qvtd-tests-all.mspec"

build

junit --launch "org.eclipse.qvtd.xtext.qvtcore.tests/.launches/org.eclipse.qvtd.xtext.qvtcore.tests\ All\ QVTcore\ Tests.launch" --flatXML --output "${checkout.location}/MMT-QVTd.test.results/org.eclipse.qvtd.xtext.qvtcore.tests.xml"
junit --launch "org.eclipse.qvtd.xtext.qvtrelation.tests/.launches/org.eclipse.qvtd.xtext.qvtrelation.tests\ All\ QVTrelation\ Tests.launch" --flatXML --output "${checkout.location}/MMT-QVTd.test.results/org.eclipse.qvtd.xtext.qvtrelation.tests.xml"

perform --properties "${checkout.location}/buildroot/build.properties" "-Dbuckminster.reference.repository=${reference.repository}" "org.eclipse.qvtd.releng.tools.build:eclipse.feature#build" 