/**
 *
 * $Id$
 */
package test.hls.HLSTree.validation;

import org.eclipse.emf.common.util.EList;

import test.hls.HLS;

import test.hls.HLSTree.HLSNode;

/**
 * A sample validator interface for {@link test.hls.HLSTree.HLSNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HLSNodeValidator {
	boolean validate();

	boolean validateParent(HLSNode value);
	boolean validateName(String value);

	boolean validateChildren(EList<HLSNode> value);
	boolean validateHls(HLS value);
}
