<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtruntimelibrary" nsURI="http://www.eclipse.org/qvt/2019/QVTruntimeLibrary"
    nsPrefix="qvtrtlib">
  <eClassifiers xsi:type="ecore:EClass" name="Extent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/ocl/2015/Library#//OclElement">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extent"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation"/>
</ecore:EPackage>
