<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="miniocl" nsURI="http://www.eclipse.org/qvtd/doc/MiniOCL/1.0"
    nsPrefix="mocl">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CallExp" abstract="true" eSuperTypes="#//OCLExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSource" lowerBound="1"
        eType="#//OCLExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/owningClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInvariants" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="#//Visitable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//NamedElement #//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="OCLExpression" eSuperTypes="#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCallExp" eSuperTypes="#//CallExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedArguments" upperBound="-1"
        eType="#//OCLExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredOperation" lowerBound="1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningClass" eType="#//Class"
        eOpposite="#//Class/ownedOperations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBodyExpression" lowerBound="1"
        eType="#//ExpressionInOCL" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//NamedElement #//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClasses" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningClass" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExp" eSuperTypes="#//CallExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredProperty" lowerBound="1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//NamedElement #//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExp" eSuperTypes="#//OCLExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visitable" instanceClassName="org.eclipse.qvtd.doc.miniocl.util.Visitable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionInOCL" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSelfVar" lowerBound="1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBody" lowerBound="1"
        eType="#//OCLExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSpecification" lowerBound="1"
        eType="#//ExpressionInOCL"/>
  </eClassifiers>
</ecore:EPackage>
