/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtcore.ui.outline;

import org.eclipse.qvtd.xtext.qvtcorebase.ui.outline.QVTcoreBaseOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class QVTcoreOutlineTreeProvider extends QVTcoreBaseOutlineTreeProvider
{
//	protected void _createNode(IOutlineNode parentNode, PredicateCS csPredicate) {
//		createNode(parentNode, csPredicate.getExpr());
//	}
}
