/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtcorebase.ui.outline;

import org.eclipse.qvtd.xtext.qvtbase.ui.outline.QVTbaseOutlineTreeProvider;
import org.eclipse.qvtd.xtext.qvtcorebasecst.AssignmentCS;
import org.eclipse.qvtd.xtext.qvtcorebasecst.QueryCS;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class QVTcoreBaseOutlineTreeProvider extends QVTbaseOutlineTreeProvider
{
	protected void _createChildren(IOutlineNode parentNode, AssignmentCS csOperator) {
		createNode(parentNode, csOperator.getInitialiser());
	}

	protected boolean _isLeaf(QueryCS csExp) {
		return csExp.getExpression() == null;
	}
}
