/**
 *
 * $Id$
 */
package org.eclipse.qvtd.compiler.internal.qvtcconfig.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.qvtd.compiler.internal.qvtcconfig.Direction;
import org.eclipse.qvtd.compiler.internal.qvtcconfig.Mode;
import org.eclipse.qvtd.compiler.internal.qvtcconfig.Transformation;

/**
 * A sample validator interface for {@link org.eclipse.qvtd.compiler.internal.qvtcconfig.Configuration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigurationValidator {
	boolean validate();

	boolean validateInputDirection(Direction value);
	boolean validateOutputDirection(EList<Direction> value);
	boolean validateMode(Mode value);
	boolean validateTransformation(Transformation value);
	boolean validateMiddle(Direction value);
}
