/**
 *
 * $Id$
 */
package org.eclipse.qvtd.compiler.internal.qvtcconfig.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.qvtd.compiler.internal.qvtcconfig.Import}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportValidator {
	boolean validate();

	boolean validateMetamodelFile(String value);
	boolean validateMetamodelUri(String value);
	boolean validatePackage(EList<String> value);
}
