/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.qvtd.doc.minioclcs.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage;
import org.eclipse.qvtd.doc.minioclcs.SelfExpCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Self Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SelfExpCSImpl extends PrimaryExpCSImpl implements SelfExpCS
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected SelfExpCSImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return MinioclcsPackage.Literals.SELF_EXP_CS;
	}

} //SelfExpCSImpl
