/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtcorebase.ui.labeling;

import org.eclipse.ocl.examples.xtext.essentialocl.ui.labeling.EssentialOCLDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class QVTcoreBaseDescriptionLabelProvider extends EssentialOCLDescriptionLabelProvider {

	// Labels and icons can be computed like this:
	
//	String text(IEObjectDescription ele) {
//	   return ele.getName();
//	}
//	 
//  String image(IEObjectDescription ele) {
//     return ele.getEClass().getName() + ".gif";
//  }	 
}
