<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtbasecs" nsURI="http://www.eclipse.org/ocl/2016/QVTbaseCS"
    nsPrefix="qvtbcs">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTransformationCS" abstract="true"
      eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ClassCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPathName" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTargets" upperBound="-1"
        eType="#//TargetCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundTargetElementCS" eSuperTypes="#//TargetElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTargetElements" upperBound="-1"
        eType="#//SimpleTargetElementCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DummyQVTbaseConstraintClass" abstract="true"
      eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="DummyConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Dummy Constraint class ensures Validator is generated"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedPackageCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PackageCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPathName" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PathNameCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleTargetElementCS" eSuperTypes="#//TargetElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#T-qvtbase-TypedModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterates" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtbase/model/QVTbase.ecore#T-qvtbase-TypedModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="via" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//NamedElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTargetElements" upperBound="-1"
        eType="#//TargetElementCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetElementCS" abstract="true" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS"/>
</ecore:EPackage>
