/*
 * generated by Xtext
 */
package org.eclipse.qvtd.xtext.qvtrelation.scoping;

import org.eclipse.ocl.examples.xtext.essentialocl.scoping.EssentialOCLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class QVTrelationScopeProvider extends EssentialOCLScopeProvider {

}
