/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.qvtd.doc.minioclcs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getBooleanLiteralExpCS()
 * @model
 * @generated
 */
public interface BooleanLiteralExpCS extends LiteralExpCS
{
} // BooleanLiteralExpCS
