/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.qvtd.doc.minioclcs;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.CollectionLiteralExpCS#getKind <em>Kind</em>}</li>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.CollectionLiteralExpCS#getParts <em>Parts</em>}</li>
 * </ul>
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getCollectionLiteralExpCS()
 * @model
 * @generated
 */
public interface CollectionLiteralExpCS extends LiteralExpCS
{
  /**
	 * Returns the value of the '<em><b>Kind</b></em>' attribute.
	 * The literals are from the enumeration {@link org.eclipse.qvtd.doc.minioclcs.CollectionKindCS}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kind</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Kind</em>' attribute.
	 * @see org.eclipse.qvtd.doc.minioclcs.CollectionKindCS
	 * @see #setKind(CollectionKindCS)
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getCollectionLiteralExpCS_Kind()
	 * @model
	 * @generated
	 */
  CollectionKindCS getKind();

  /**
	 * Sets the value of the '{@link org.eclipse.qvtd.doc.minioclcs.CollectionLiteralExpCS#getKind <em>Kind</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Kind</em>' attribute.
	 * @see org.eclipse.qvtd.doc.minioclcs.CollectionKindCS
	 * @see #getKind()
	 * @generated
	 */
  void setKind(CollectionKindCS value);

  /**
	 * Returns the value of the '<em><b>Parts</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.qvtd.doc.minioclcs.CollectionLiteralPartCS}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Parts</em>' containment reference list.
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getCollectionLiteralExpCS_Parts()
	 * @model containment="true"
	 * @generated
	 */
  EList<CollectionLiteralPartCS> getParts();

} // CollectionLiteralExpCS
