/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.eclipse.qvtd.doc.minioclcs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getExpCS()
 * @model
 * @generated
 */
public interface ExpCS extends CSTrace
{
} // ExpCS
