/*******************************************************************************
 * Copyright (c) 2019 Willink Transformations and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 *     E.D.Willink - initial API and implementation
 *******************************************************************************/
/**
 * generated by Xtext 2.16.0
 */
package org.eclipse.qvtd.doc.minioclcs;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.ImportCS#getAlias <em>Alias</em>}</li>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.ImportCS#getUri <em>Uri</em>}</li>
 * </ul>
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getImportCS()
 * @model
 * @generated
 */
public interface ImportCS extends CSTrace
{
  /**
	 * Returns the value of the '<em><b>Alias</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Alias</em>' attribute.
	 * @see #setAlias(String)
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getImportCS_Alias()
	 * @model
	 * @generated
	 */
  String getAlias();

  /**
	 * Sets the value of the '{@link org.eclipse.qvtd.doc.minioclcs.ImportCS#getAlias <em>Alias</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Alias</em>' attribute.
	 * @see #getAlias()
	 * @generated
	 */
  void setAlias(String value);

  /**
	 * Returns the value of the '<em><b>Uri</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Uri</em>' attribute.
	 * @see #setUri(String)
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getImportCS_Uri()
	 * @model
	 * @generated
	 */
  String getUri();

  /**
	 * Sets the value of the '{@link org.eclipse.qvtd.doc.minioclcs.ImportCS#getUri <em>Uri</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Uri</em>' attribute.
	 * @see #getUri()
	 * @generated
	 */
  void setUri(String value);

} // ImportCS
