/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.qvtd.doc.minioclcs;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.LetExpCS#getLetVars <em>Let Vars</em>}</li>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.LetExpCS#getInExp <em>In Exp</em>}</li>
 * </ul>
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getLetExpCS()
 * @model
 * @generated
 */
public interface LetExpCS extends PrimaryExpCS
{
  /**
	 * Returns the value of the '<em><b>Let Vars</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.qvtd.doc.minioclcs.LetVarCS}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Let Vars</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Let Vars</em>' containment reference list.
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getLetExpCS_LetVars()
	 * @model containment="true"
	 * @generated
	 */
  EList<LetVarCS> getLetVars();

  /**
	 * Returns the value of the '<em><b>In Exp</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>In Exp</em>' containment reference.
	 * @see #setInExp(ExpCS)
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getLetExpCS_InExp()
	 * @model containment="true"
	 * @generated
	 */
  ExpCS getInExp();

  /**
	 * Sets the value of the '{@link org.eclipse.qvtd.doc.minioclcs.LetExpCS#getInExp <em>In Exp</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>In Exp</em>' containment reference.
	 * @see #getInExp()
	 * @generated
	 */
  void setInExp(ExpCS value);

} // LetExpCS
