/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.qvtd.doc.minioclcs;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Name CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.PathNameCS#getPathElements <em>Path Elements</em>}</li>
 * </ul>
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getPathNameCS()
 * @model
 * @generated
 */
public interface PathNameCS extends CSTrace
{
  /**
	 * Returns the value of the '<em><b>Path Elements</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.qvtd.doc.minioclcs.PathElementCS}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Path Elements</em>' containment reference list.
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getPathNameCS_PathElements()
	 * @model containment="true"
	 * @generated
	 */
  EList<PathElementCS> getPathElements();

} // PathNameCS
