/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.qvtd.doc.minioclcs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.qvtd.doc.minioclcs.StringLiteralExpCS#getStringSymbol <em>String Symbol</em>}</li>
 * </ul>
 *
 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getStringLiteralExpCS()
 * @model
 * @generated
 */
public interface StringLiteralExpCS extends LiteralExpCS
{
  /**
	 * Returns the value of the '<em><b>String Symbol</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Symbol</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>String Symbol</em>' attribute.
	 * @see #setStringSymbol(String)
	 * @see org.eclipse.qvtd.doc.minioclcs.MinioclcsPackage#getStringLiteralExpCS_StringSymbol()
	 * @model
	 * @generated
	 */
  String getStringSymbol();

  /**
	 * Sets the value of the '{@link org.eclipse.qvtd.doc.minioclcs.StringLiteralExpCS#getStringSymbol <em>String Symbol</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>String Symbol</em>' attribute.
	 * @see #getStringSymbol()
	 * @generated
	 */
  void setStringSymbol(String value);

} // StringLiteralExpCS
