/**
 *
 * $Id$
 */
package test.umltordbms.validation;

import test.simplerdbms.ForeignKey;

import test.simpleuml.Association;

import test.umltordbms.ClassToTable;

/**
 * A sample validator interface for {@link test.umltordbms.AssociationToForeignKey}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationToForeignKeyValidator {
	boolean validate();

	boolean validateAssociation(Association value);
	boolean validateForeignKey(ForeignKey value);
	boolean validateOwner(ClassToTable value);
	boolean validateReferenced(ClassToTable value);
}
