/**
 *
 * $Id$
 */
package test.umltordbms.validation;

import org.eclipse.emf.common.util.EList;

import test.simplerdbms.Key;
import test.simplerdbms.Table;

import test.umltordbms.AssociationToForeignKey;
import test.umltordbms.PackageToSchema;

/**
 * A sample validator interface for {@link test.umltordbms.ClassToTable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassToTableValidator {
	boolean validate();

	boolean validateAssociationsToForeignKeys(EList<AssociationToForeignKey> value);
	boolean validateOwner(PackageToSchema value);
	boolean validatePrimaryKey(Key value);
	boolean validateTable(Table value);
	boolean validateUmlClass(test.simpleuml.Class value);
}
