/**
 *
 * $Id$
 */
package test.umltordbms.validation;

import org.eclipse.emf.common.util.EList;

import test.simpleuml.Attribute;

import test.umltordbms.AttributeToColumn;
import test.umltordbms.FromAttributeOwner;

/**
 * A sample validator interface for {@link test.umltordbms.FromAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FromAttributeValidator {
	boolean validate();

	boolean validateKind(String value);
	boolean validateAttribute(Attribute value);
	boolean validateLeafs(EList<AttributeToColumn> value);
	boolean validateOwner(FromAttributeOwner value);
}
