/**
 *
 * $Id$
 */
package test.umltordbms.validation;

import org.eclipse.emf.common.util.EList;

import test.umltordbms.FromAttribute;

/**
 * A sample validator interface for {@link test.umltordbms.FromAttributeOwner}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FromAttributeOwnerValidator {
	boolean validate();

	boolean validateFromAttributes(EList<FromAttribute> value);
}
