/**
 *
 * $Id$
 */
package test.umltordbms.validation;

import org.eclipse.emf.common.util.EList;

import test.simplerdbms.Schema;

import test.umltordbms.ClassToTable;
import test.umltordbms.PrimitiveToName;

/**
 * A sample validator interface for {@link test.umltordbms.PackageToSchema}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageToSchemaValidator {
	boolean validate();

	boolean validateClassesToTables(EList<ClassToTable> value);
	boolean validatePrimitivesToNames(EList<PrimitiveToName> value);
	boolean validateSchema(Schema value);
	boolean validateUmlPackage(test.simpleuml.Package value);
}
