/**
 *
 * $Id$
 */
package test.umltordbms.validation;

import test.simpleuml.PrimitiveDataType;

import test.umltordbms.PackageToSchema;

/**
 * A sample validator interface for {@link test.umltordbms.PrimitiveToName}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PrimitiveToNameValidator {
	boolean validate();

	boolean validateTypeName(String value);
	boolean validateOwner(PackageToSchema value);
	boolean validatePrimitive(PrimitiveDataType value);
}
