/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.eclipse.qvtd.doc.ui.outline


/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
public class MiniOCLCSCS2ASOutlineTreeProvider extends org.eclipse.qvtd.doc.ui.outline.CS2ASOutlineTreeProvider {
	
}
