/**
 *
 * $Id$
 */
package test.hsv.HSVTree.validation;

import org.eclipse.emf.common.util.EList;

import test.hsv.HSV;

import test.hsv.HSVTree.HSVNode;

/**
 * A sample validator interface for {@link test.hsv.HSVTree.HSVNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HSVNodeValidator {
	boolean validate();

	boolean validateParent(HSVNode value);
	boolean validateName(String value);

	boolean validateChildren(EList<HSVNode> value);
	boolean validateHsv(HSV value);
}
