<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvttrace" nsURI="http://www.eclipse.org/qvt/2018/QVTtrace" nsPrefix="qvttrace">
  <eClassifiers xsi:type="ecore:EClass" name="Dispatch" abstract="true" eSuperTypes="#//TraceInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="success" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Execution" abstract="true" eSuperTypes="#//TraceInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="TraceElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TraceInstance" abstract="true" eSuperTypes="#//TraceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningModel" eType="#//TraceModel"
        eOpposite="#//TraceModel/ownedTraces">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Rule represented by this RuleRegion."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceModel" eSuperTypes="#//TraceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTraces" upperBound="-1"
        eType="#//TraceInstance" containment="true" eOpposite="#//TraceInstance/owningModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationExecution" abstract="true"
      eSuperTypes="#//Execution"/>
</ecore:EPackage>
