/**
 *
 * $Id$
 */
package test.simpleuml.validation;


/**
 * A sample validator interface for {@link test.simpleuml.Association}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationValidator {
	boolean validate();

	boolean validateDestination(test.simpleuml.Class value);
	boolean validateSource(test.simpleuml.Class value);
}
