/**
 *
 * $Id$
 */
package test.simpleuml.validation;

import org.eclipse.emf.common.util.EList;

import test.simpleuml.Association;
import test.simpleuml.Attribute;

/**
 * A sample validator interface for {@link test.simpleuml.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateAttributes(EList<Attribute> value);
	boolean validateForward(EList<Association> value);
	boolean validateGeneral(EList<test.simpleuml.Class> value);
	boolean validateGeneralOpposite(EList<test.simpleuml.Class> value);
	boolean validateReverse(EList<Association> value);
}
