/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.eclipse.qvtd.doc.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.qvtd.doc.minioclcs.RootCS

@RunWith(XtextRunner)
@InjectWith(MiniOCLCSInjectorProvider)
class MiniOCLCSParsingTest{

	@Inject
	ParseHelper<RootCS> parseHelper

	@Test 
	def void testSimpleMiniOCL() {
		val result = parseHelper.parse('''
			package ocl {
				
				class String {}
			}
			
			package package1 {
				
				class c1 {		
					prop a : ocl::String;
					op getA() : ocl::String = a;
				}
			}

		''')
		Assert.assertNotNull(result)
	}

	//@Test 
	def void test() {
		val result = parseHelper.parse('''
			package package1 {
				
				class c1 {
					
					prop a : String;
					
					op giveMeA() : String = self.c1;
					
					op testA() : Boolean = giveMeA().size() <> 0; 
				}
			}
			
			context package1::c1 {
				inv : a = giveMeA();
				inv : testA();
			}
		''')
		Assert.assertNotNull(result)
	}

}
