<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FamilyPlans" nsURI="http://www.eclipse.org/qvtd/xtext/qvtrelation/tests/Persons2Families/1.0/FamilyPlans"
    nsPrefix="FamilyPlans">
  <eClassifiers xsi:type="ecore:EClass" name="DaughterPlan" eSuperTypes="#//FamilyMemberPlan"/>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyMemberPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyMember" lowerBound="1"
        eType="ecore:EClass Families.ecore#//FamilyMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyPlan" lowerBound="1"
        eType="#//FamilyPlan" eOpposite="#//FamilyPlan/familyMemberPlans"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="family" eType="ecore:EClass Families.ecore#//Family"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyMemberPlans" upperBound="-1"
        eType="#//FamilyMemberPlan" containment="true" eOpposite="#//FamilyMemberPlan/familyPlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="surnamePlan" lowerBound="1"
        eType="#//SurnamePlan" eOpposite="#//SurnamePlan/familyPlans"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyPlanning">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surnamePlans" upperBound="-1"
        eType="#//SurnamePlan" containment="true" eOpposite="#//SurnamePlan/familyPlanning"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debugNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FatherPlan" eSuperTypes="#//FamilyMemberPlan"/>
  <eClassifiers xsi:type="ecore:EClass" name="MotherPlan" eSuperTypes="#//FamilyMemberPlan"/>
  <eClassifiers xsi:type="ecore:EClass" name="SonPlan" eSuperTypes="#//FamilyMemberPlan"/>
  <eClassifiers xsi:type="ecore:EClass" name="SurnamePlan">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyPlans" upperBound="-1"
        eType="#//FamilyPlan" containment="true" eOpposite="#//FamilyPlan/surnamePlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familyPlanning" lowerBound="1"
        eType="#//FamilyPlanning" eOpposite="#//FamilyPlanning/surnamePlans"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="families" upperBound="-1"
        eType="ecore:EClass Families.ecore#//Family"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="females" upperBound="-1"
        eType="ecore:EClass Persons.ecore#//Female"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="males" upperBound="-1"
        eType="ecore:EClass Persons.ecore#//Male"/>
  </eClassifiers>
</ecore:EPackage>
