<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PSeqToStm" nsURI="PSeqToStm" nsPrefix="s2s">
  <eClassifiers xsi:type="ecore:EClass" name="TInteractionToStateMachine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sn" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="i" lowerBound="1" eType="ecore:EClass SeqMM.ecore#//Interaction">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TInteractionToStateMachine"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" lowerBound="1" eType="ecore:EClass StmcMM.ecore#//StateMachine">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TInteractionToStateMachine"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TStateToState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sn" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="st1" lowerBound="1" eType="ecore:EClass SeqMM.ecore#//State">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TStateToState"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l" lowerBound="1" eType="ecore:EClass SeqMM.ecore#//LifeLine">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TStateToState"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="i" lowerBound="1" eType="ecore:EClass SeqMM.ecore#//Interaction">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TStateToState"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="st2" lowerBound="1" eType="ecore:EClass StmcMM.ecore#//State">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TStateToState"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" lowerBound="1" eType="ecore:EClass StmcMM.ecore#//StateMachine">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="TStateToState"/>
        <details key="lower" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
