<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="umlx" nsURI="http://www.eclipse.org/qvt/2016/UMLX" nsPrefix="umlx">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/diagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningSource" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/ownedOutgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incomingEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDiagrams" upperBound="-1"
        eType="#//TxDiagram" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//Diagram" eOpposite="#//Diagram/ownedNodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOutgoingEdges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/owningSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelDiagram" eSuperTypes="#//Diagram"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelDomainNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredTypedModelNode"
        lowerBound="1" eType="#//TxTypedModelNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootPatternNodes" lowerBound="1"
        upperBound="-1" eType="#//RelPatternNode" eOpposite="#//RelPatternNode/relDomainNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelInvocationEdge" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelInvocationNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWhen" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelPatternEdge" eSuperTypes="#//Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredProperty" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelPatternNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredClass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relDomainNode" eType="#//RelDomainNode"
        eOpposite="#//RelDomainNode/rootPatternNodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TxDiagram" eSuperTypes="#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDiagrams" upperBound="-1"
        eType="#//RelDiagram" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TxEdge" abstract="true" eSuperTypes="#//Edge"/>
  <eClassifiers xsi:type="ecore:EClass" name="TxNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="TxPackageNode" eSuperTypes="#//TxNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredPackage" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TxTransformationNode" eSuperTypes="#//TxNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="txTypedModelNodes" upperBound="-1"
        eType="#//TxTypedModelNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TxTypedModelNode" eSuperTypes="#//TxNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="txPackageNodes" upperBound="-1"
        eType="#//TxPackageNode"/>
  </eClassifiers>
</ecore:EPackage>
