<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvticgmodel" nsURI="http://www.eclipse.org/qvti/0.12.0/CG" nsPrefix="qvticg">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The QVTiCGModel exends the Code Generation friendly form of the OCL Pivot model with QVTi-specific constructs."/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CGConnectionAssignment" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionVariable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGVariable"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInitValue" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningMapping" lowerBound="1"
        eType="#//CGMapping" resolveProxies="false" eOpposite="#//CGMapping/ownedConnectionAssignments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGConnectionVariable" eSuperTypes="#//CGGuardVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGEcoreRealizedVariable" eSuperTypes="#//CGRealizedVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGFunction" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGFunctionCallExp" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGOperationCallExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//CGFunction" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGFunctionParameter" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//CGFunction" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGGuardVariable" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningMapping" lowerBound="1"
        eType="#//CGMapping" resolveProxies="false" eOpposite="#//CGMapping/ownedGuardVariables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" lowerBound="1"
        eType="#//CGTypedModel" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGMapping" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBody" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConnectionAssignments"
        upperBound="-1" eType="#//CGConnectionAssignment" containment="true" resolveProxies="false"
        eOpposite="#//CGConnectionAssignment/owningMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedGuardVariables" ordered="false"
        upperBound="-1" eType="#//CGGuardVariable" containment="true" resolveProxies="false"
        eOpposite="#//CGGuardVariable/owningMapping">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parameters of this operation, with 'self' as the first parameter."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRealizedVariables"
        upperBound="-1" eType="#//CGRealizedVariable" containment="true" resolveProxies="false"
        eOpposite="#//CGRealizedVariable/owningMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningTransformation" lowerBound="1"
        eType="#//CGTransformation" resolveProxies="false" eOpposite="#//CGTransformation/ownedMappings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGMappingCall" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMappingCallBindings"
        upperBound="-1" eType="#//CGMappingCallBinding" containment="true" resolveProxies="false"
        eOpposite="#//CGMappingCallBinding/owningMappingCall"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredMapping" lowerBound="1"
        eType="#//CGMapping" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The this expression for the call when invoking a native or ecore implementation."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGMappingCallBinding" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedValue" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningMappingCall" lowerBound="1"
        eType="#//CGMappingCall" resolveProxies="false" eOpposite="#//CGMappingCall/ownedMappingCallBindings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGMappingExp" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAccumulators" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGAccumulator"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBody" eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGMappingLoop" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGIterationCallExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGMiddlePropertyAssignment" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGEcorePropertyAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGMiddlePropertyCallExp" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGOppositePropertyCallExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGRealizedVariable" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executorType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGExecutorType"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The shared type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningMapping" lowerBound="1"
        eType="#//CGMapping" resolveProxies="false" eOpposite="#//CGMapping/ownedRealizedVariables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" lowerBound="1"
        eType="#//CGTypedModel" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//CGRealizedVariablePart" containment="true" resolveProxies="false"
        eOpposite="#//CGRealizedVariablePart/owningRealizedVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGRealizedVariablePart" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningRealizedVariable"
        lowerBound="1" eType="#//CGRealizedVariable" resolveProxies="false" eOpposite="#//CGRealizedVariable/ownedParts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" lowerBound="1" eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredProperty" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGProperty"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The shared type."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGSpeculateExp" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" lowerBound="1" upperBound="-1"
        eType="#//CGSpeculatePart" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="speculated" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGSpeculatePart" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectExp" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eStructuralFeature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGTransformation" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMappings" lowerBound="1"
        upperBound="-1" eType="#//CGMapping" containment="true" resolveProxies="false"
        eOpposite="#//CGMapping/owningTransformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTypedModels" upperBound="-1"
        eType="#//CGTypedModel" containment="true" resolveProxies="false" eOpposite="#//CGTypedModel/owningTransformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CGTypedModel" eSuperTypes="../../org.eclipse.ocl.examples.codegen/model/cgmodel.ecore#//CGValuedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningTransformation" lowerBound="1"
        eType="#//CGTransformation" resolveProxies="false" eOpposite="#//CGTransformation/ownedTypedModels"/>
  </eClassifiers>
</ecore:EPackage>
