/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.qvtd.cs2as.compiler.tests.models.companies.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCompaniesValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs2as/tests/companies/CS/1.0"));
		return result;
	}
	
}
