<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HSV2HSL" nsURI="http://www.eclipse.org/qvtd/xtext/qvtcore/tests/HSV2HSL/1.0/HSVtoHSL"
    nsPrefix="hsv2hsl">
  <eClassifiers xsi:type="ecore:EDataType" name="RGB" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="HSVNode2HSLNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//HSVNode2HSLNode"
        eOpposite="#//HSVNode2HSLNode/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//HSVNode2HSLNode" containment="true" eOpposite="#//HSVNode2HSLNode/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hsv" lowerBound="1" eType="ecore:EClass HSVTree.ecore#//HSVNode">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="middle"/>
        <details key="upper" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hsl" lowerBound="1" eType="ecore:EClass HSLTree.ecore#//HSLNode">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="middle"/>
        <details key="upper" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rgb" lowerBound="1" eType="#//RGB"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
