<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtscheduling" nsURI="http://www.eclipse.org/qvt/0.1/QVTscheduling/"
    nsPrefix="qvtscheduling">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//AbstractAction" eOpposite="#//AbstractAction/results"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryDistinctData" upperBound="-1"
        eType="#//DistinctData" eOpposite="#//DistinctData/primaryArgument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryDistinctData"
        upperBound="-1" eType="#//DistinctData" eOpposite="#//DistinctData/secondaryArgument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//AbstractDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//AbstractDatum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="ecore:EClass http://www.eclipse.org/qvt/0.9/QVTcoreBase#//CoreDomain"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//AbstractAction" derived="true" eOpposite="#//AbstractAction/arguments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schdule" eType="#//Schedule"
        eOpposite="#//Schedule/datums"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/sources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distinctArguments" upperBound="-1"
        eType="#//DistinctData" containment="true" eOpposite="#//DistinctData/target"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//AbstractAction"
        eOpposite="#//AbstractAction/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//AbstractAction" eOpposite="#//AbstractAction/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//AbstractDatum" derived="true" eOpposite="#//AbstractDatum/targets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" eType="#//Schedule"
        eOpposite="#//Schedule/actions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedVariables" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/qvt/0.9/QVTcoreBase#//RealizedVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDatum" eSuperTypes="#//AbstractDatum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistinctData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//AbstractAction"
        eOpposite="#//AbstractAction/distinctArguments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryArgument" lowerBound="1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/primaryDistinctData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryArgument" upperBound="-1"
        eType="#//AbstractDatum" eOpposite="#//AbstractDatum/secondaryDistinctData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputAction" eSuperTypes="#//AbstractAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingAction" eSuperTypes="#//AbstractAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingBindings" upperBound="-1"
        eType="#//MappingBinding" containment="true" eOpposite="#//MappingBinding/mappingAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/qvt/0.9/QVTimperative#//Mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingAction" eType="#//MappingAction"
        eOpposite="#//MappingAction/mappingBindings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datum" eType="#//PropertyDatum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputAction" eSuperTypes="#//AbstractAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datums" upperBound="-1"
        eType="#//AbstractDatum" containment="true" eOpposite="#//AbstractDatum/schdule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//AbstractAction" containment="true" eOpposite="#//AbstractAction/schedule"/>
  </eClassifiers>
</ecore:EPackage>
