<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="qvtschedule"
    nsURI="http://www.eclipse.org/qvt/0.1/QVTschedule/"
    nsPrefix="qvtschedule">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractDependency"
      abstract="true">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="origins"
        upperBound="-1"
        eType="#//AbstractAction"
        eOpposite="#//AbstractAction/dataHooks"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dependents"
        upperBound="-1"
        eType="#//AbstractAction"
        eOpposite="#//AbstractAction/dataDependencies"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="super"
        upperBound="-1"
        eType="#//AbstractDependency"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="type"
        lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Type"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="domain"
        eType="ecore:EClass http://www.eclipse.org/qvt/0.9/QVTcoreBase#//CoreDomain"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="schdule"
        eType="#//Schedule"
        eOpposite="#//Schedule/abstractDepedencies"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractAction"
      abstract="true">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dataHooks"
        upperBound="-1"
        eType="#//AbstractDependency"
        eOpposite="#//AbstractDependency/origins"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dataDependencies"
        lowerBound="1"
        upperBound="-1"
        eType="#//AbstractDependency"
        volatile="true"
        eOpposite="#//AbstractDependency/dependents">
      <eAnnotations
          source="OCL">
        <details
            key="derived"
            value="self.distinctArguments.collect(da | da.secondaryArgument.including(da.primaryArgument))"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="arguments"
        upperBound="-1"
        eType="#//InputParameter"
        containment="true"
        eOpposite="#//InputParameter/target"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="results"
        upperBound="-1"
        eType="#//OutputParameter"
        containment="true"
        eOpposite="#//OutputParameter/source"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="index"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parent"
        eType="#//AbstractAction"
        eOpposite="#//AbstractAction/children"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="children"
        upperBound="-1"
        eType="#//AbstractAction"
        eOpposite="#//AbstractAction/parent"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="schedule"
        eType="#//Schedule"
        eOpposite="#//Schedule/abstractActions"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ClassDependency"
      eSuperTypes="#//AbstractDependency">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parameters"
        upperBound="-1"
        eType="#//Parameter"
        eOpposite="#//Parameter/classDependency"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PropertyDependency"
      eSuperTypes="#//AbstractDependency">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="property"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Property"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Parameter"
      abstract="true">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="classDependency"
        lowerBound="1"
        eType="#//ClassDependency"
        eOpposite="#//ClassDependency/parameters"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variable"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Variable"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InputParameter"
      eSuperTypes="#//Parameter">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="target"
        lowerBound="1"
        eType="#//AbstractAction"
        eOpposite="#//AbstractAction/arguments"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="secondaryArgumentRelations"
        upperBound="-1"
        eType="#//SecondaryArgumentRelation"
        containment="true"
        eOpposite="#//SecondaryArgumentRelation/primaryArgument"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OutputParameter"
      eSuperTypes="#//Parameter">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="source"
        lowerBound="1"
        eType="#//AbstractAction"
        eOpposite="#//AbstractAction/results"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SecondaryArgumentRelation">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="primaryArgument"
        eType="#//InputParameter"
        eOpposite="#//InputParameter/secondaryArgumentRelations"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="relation"
        lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//OCLExpression"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="argument"
        lowerBound="1"
        eType="#//InputParameter"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InputAction"
      eSuperTypes="#//AbstractAction"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MappingAction"
      eSuperTypes="#//AbstractAction">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="mappingBindings"
        upperBound="-1"
        eType="#//MappingBinding"
        containment="true"
        eOpposite="#//MappingBinding/mappingAction"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="mapping"
        lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/qvt/0.9/QVTimperative#//Mapping"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MappingBinding">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="mappingAction"
        eType="#//MappingAction"
        eOpposite="#//MappingAction/mappingBindings"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="loop"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bindingExp"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//OCLExpression"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="boundVariable"
        eType="ecore:EClass http://www.eclipse.org/ocl/3.1.0/Pivot#//Variable"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OutputAction"
      eSuperTypes="#//AbstractAction"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Schedule">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="abstractDepedencies"
        upperBound="-1"
        eType="#//AbstractDependency"
        containment="true"
        eOpposite="#//AbstractDependency/schdule"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="abstractActions"
        upperBound="-1"
        eType="#//AbstractAction"
        containment="true"
        eOpposite="#//AbstractAction/schedule"/>
  </eClassifiers>
</ecore:EPackage>
