<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ClassMM" nsURI="http://www.eclipse.org/qvtd/xtext/qvtrelation/tests/classmodel2classmodel/ClassMM"
    nsPrefix="cmm">
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subs" ordered="false" upperBound="-1"
        eType="#//Class" eOpposite="#//Class/supers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supers" ordered="false"
        upperBound="-1" eType="#//Class" eOpposite="#//Class/subs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
