/**
* Essential OCL Grammar
* <copyright>
*
* Copyright (c) 2005, 2009 IBM Corporation and others.
* All rights reserved.   This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*   IBM - Initial API and implementation
*   E.D.Willink - Elimination of some shift-reduce conflicts
*   E.D.Willink - Remove unnecessary warning suppression
*   E.D.Willink - Bugs 184048, 225493, 243976, 259818, 282882, 287993, 288040, 292112
*   Borland - Bug 242880
*   E.D.Willink - Extended API and implementation for QVTr
*
* </copyright>
*
* $Id: QVTrParsersym.java,v 1.12 2009/10/21 07:49:03 ewillink Exp $
*/

package org.eclipse.qvt.declarative.parser.qvtrelation;

public interface QVTrParsersym {
    public final static int
      TK_PLUS_PLUS = 86,
      TK_STRING_LITERAL = 43,
      TK_INTEGER_LITERAL = 44,
      TK_REAL_LITERAL = 45,
      TK_PLUS = 70,
      TK_MINUS = 32,
      TK_MULTIPLY = 38,
      TK_DIVIDE = 71,
      TK_GREATER = 72,
      TK_LESS = 73,
      TK_EQUAL = 68,
      TK_GREATER_EQUAL = 74,
      TK_LESS_EQUAL = 75,
      TK_NOT_EQUAL = 76,
      TK_LPAREN = 2,
      TK_RPAREN = 6,
      TK_LBRACE = 39,
      TK_RBRACE = 41,
      TK_LBRACKET = 50,
      TK_RBRACKET = 82,
      TK_ARROW = 83,
      TK_BAR = 69,
      TK_COMMA = 40,
      TK_COLON = 3,
      TK_COLONCOLON = 33,
      TK_SEMICOLON = 51,
      TK_DOT = 77,
      TK_DOTDOT = 87,
      TK_self = 4,
      TK_if = 46,
      TK_then = 88,
      TK_else = 89,
      TK_endif = 84,
      TK_and = 78,
      TK_or = 79,
      TK_xor = 80,
      TK_not = 47,
      TK_implies = 85,
      TK_let = 48,
      TK_in = 90,
      TK_true = 34,
      TK_false = 35,
      TK_null = 36,
      TK_invalid = 37,
      TK_Set = 7,
      TK_Bag = 8,
      TK_Sequence = 9,
      TK_Collection = 10,
      TK_OrderedSet = 11,
      TK_iterate = 12,
      TK_forAll = 13,
      TK_exists = 14,
      TK_isUnique = 15,
      TK_any = 16,
      TK_one = 17,
      TK_collect = 18,
      TK_select = 19,
      TK_reject = 20,
      TK_collectNested = 21,
      TK_sortedBy = 22,
      TK_closure = 23,
      TK_String = 24,
      TK_Integer = 25,
      TK_UnlimitedNatural = 26,
      TK_Real = 27,
      TK_Boolean = 28,
      TK_Tuple = 42,
      TK_OclAny = 29,
      TK_OclVoid = 30,
      TK_OclInvalid = 31,
      TK_checkonly = 55,
      TK_default_values = 53,
      TK_domain = 49,
      TK_enforce = 56,
      TK_extends = 57,
      TK_implementedby = 58,
      TK_import = 59,
      TK_key = 60,
      TK_overrides = 61,
      TK_primitive = 62,
      TK_query = 63,
      TK_relation = 54,
      TK_replace = 64,
      TK_top = 65,
      TK_transformation = 52,
      TK_when = 66,
      TK_where = 67,
      TK_EOF_TOKEN = 81,
      TK_IDENTIFIER = 5,
      TK_SINGLE_LINE_COMMENT = 91,
      TK_MULTI_LINE_COMMENT = 92,
      TK_ERROR_TOKEN = 1;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "ERROR_TOKEN",
                 "LPAREN",
                 "COLON",
                 "self",
                 "IDENTIFIER",
                 "RPAREN",
                 "Set",
                 "Bag",
                 "Sequence",
                 "Collection",
                 "OrderedSet",
                 "iterate",
                 "forAll",
                 "exists",
                 "isUnique",
                 "any",
                 "one",
                 "collect",
                 "select",
                 "reject",
                 "collectNested",
                 "sortedBy",
                 "closure",
                 "String",
                 "Integer",
                 "UnlimitedNatural",
                 "Real",
                 "Boolean",
                 "OclAny",
                 "OclVoid",
                 "OclInvalid",
                 "MINUS",
                 "COLONCOLON",
                 "true",
                 "false",
                 "null",
                 "invalid",
                 "MULTIPLY",
                 "LBRACE",
                 "COMMA",
                 "RBRACE",
                 "Tuple",
                 "STRING_LITERAL",
                 "INTEGER_LITERAL",
                 "REAL_LITERAL",
                 "if",
                 "not",
                 "let",
                 "domain",
                 "LBRACKET",
                 "SEMICOLON",
                 "transformation",
                 "default_values",
                 "relation",
                 "checkonly",
                 "enforce",
                 "extends",
                 "implementedby",
                 "import",
                 "key",
                 "overrides",
                 "primitive",
                 "query",
                 "replace",
                 "top",
                 "when",
                 "where",
                 "EQUAL",
                 "BAR",
                 "PLUS",
                 "DIVIDE",
                 "GREATER",
                 "LESS",
                 "GREATER_EQUAL",
                 "LESS_EQUAL",
                 "NOT_EQUAL",
                 "DOT",
                 "and",
                 "or",
                 "xor",
                 "EOF_TOKEN",
                 "RBRACKET",
                 "ARROW",
                 "endif",
                 "implies",
                 "PLUS_PLUS",
                 "DOTDOT",
                 "then",
                 "else",
                 "in",
                 "SINGLE_LINE_COMMENT",
                 "MULTI_LINE_COMMENT"
             };

    public final static boolean isValidForParser = true;
}
