/*
 * generated by Xtext
 */
package org.eclipse.qvtd.xtext.qvtcore.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.qvtd.xtext.qvtcore.ui.internal.QVTcoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QVTcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QVTcoreActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QVTcoreActivator.getInstance().getInjector(QVTcoreActivator.ORG_ECLIPSE_QVTD_XTEXT_QVTCORE_QVTCORE);
	}
	
}
