/*
* generated by Xtext
*/
package org.eclipse.qvtd.xtext.qvtimperative.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QVTimperativeProposalProvider extends AbstractQVTimperativeProposalProvider {

}
